export const MenuData = [
  {id: 1, path: '/', name: 'ToDo'},
  {id: 2, path: '/bank', name: 'Bank'},
  {id: 3, path: '/crosses', name: 'Crosses'},
  {id: 4, path: '/modal', name: 'Modal'},
  {id: 5, path: '/atm', name: 'ATM'},
  {id: 6, path: '/s2hw1', name: 'S2-HW1'},
  {id: 7, path: '/s2eLesson1', name: 'S2eLesson1'},
  {id: 8, path: '/s2eLesson2', name: 'S2eLesson2'},
  {id: 9, path: '/s2eLesson3', name: 'S2eLesson3'},
  {id: 10, path: '/LSCounter', name: 'LS Counter'},
  {id: 11, path: '/MaterialUI', name: 'MaterialUI'},
  {id: 12, path: '/ReducerTests', name: 'Reducer + Tests'},
  {id: 13, path: '/ReduxTK', name: 'ReduxTK'},
  {id: 14, path: '/Sp3L2Todo', name: 'Sp3L2Todo'},
  {id: 15, path: '/Sp3L3Todo', name: 'Sp3L3Todo'},
];